<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SHREESHA" failures="1" tests="3" name="Test" time="9.574" errors="0" timestamp="2025-04-08T18:23:31 IST">
  <testcase classname="testNgListener.AutomationTets" name="testlogo" time="2.103"/>
  <testcase classname="testNgListener.AutomationTets" name="testURL" time="0.019">
    <failure type="java.lang.AssertionError" message="expected [https://testautomationpractice.blogspot/] but found [https://testautomationpractice.blogspot.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://testautomationpractice.blogspot/] but found [https://testautomationpractice.blogspot.com/]
at testNgListener.AutomationTets.testURL(AutomationTets.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testURL -->
  <testcase classname="testNgListener.AutomationTets" name="tesTtitle" time="0.0">
    <skipped/>
  </testcase> <!-- tesTtitle -->
</testsuite> <!-- Test -->
